dist: xenial
language: emacs-lisp
addons:
  apt:
    packages:
      - gnutls-bin
      - aspell-en
      - maildir-utils
      - mu4e
cache:
  timeout: 1200
  directories:
  - $HOME/.emacs.d/elpa

matrix:
  fast_finish: true
  allow_failures:
  - env: EVM_EMACS=emacs-git-snapshot-travis
env:
  matrix:
    - EVM_EMACS=emacs-24.4-travis
    - EVM_EMACS=emacs-24.5-travis
    - EVM_EMACS=emacs-25.1-travis
    - EVM_EMACS=emacs-25.2-travis
    - EVM_EMACS=emacs-25.3-travis
    - EVM_EMACS=emacs-26.1-travis
    - EVM_EMACS=remacs-git-snapshot-travis
before_install:
  - export PATH="/home/travis/.cask/bin:/home/travis/.evm/bin:$PATH"
install:
  - git clone https://github.com/rejeep/evm.git /home/travis/.evm
  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip
  - ./setup_emacs.sh
script:
  - ./tests/check_daemon_starts.sh 0
  - ./tests/check_daemon_starts.sh 1
  - emacs -q --batch -l "tests/my-ert.el" -f ert-run-tests-batch-and-exit
  - emacs -q --batch -l "~/.emacs.d/mininit.el" -l "tests/my-ert.el" -f ert-run-tests-batch-and-exit
