sudo: false
language: emacs-lisp
env:
  - EVM_EMACS=emacs-24.3-travis
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - ./setup_emacs.sh
script:
  - ./tests/check_daemon_starts.sh 0
  - ./tests/install_pkgs.sh
  - ./tests/check_daemon_starts.sh 1
  - ./tests/check_init_compiles.sh
  - emacs -q --batch -l "tests/my-ert.el" -f ert-run-tests-batch-and-exit

