sudo: false
dist: trusty
language: emacs-lisp
addons:
  apt:
    packages:
      - aspell-en
      - maildir-utils
      - mu4e
env:
  - EVM_EMACS=
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26-pretest
  - EVM_EMACS=emacs-git-snapshot-travis
install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - if [ -n "$EVM_EMACS" ]; then evm install $EVM_EMACS --use --skip ; fi
  - ./setup_emacs.sh
script:
  - ./tests/check_daemon_starts.sh 0
  - ./tests/check_daemon_starts.sh 1
  - emacs -q --batch -l "tests/my-ert.el" -f ert-run-tests-batch-and-exit
  - emacs -q --batch -l "~/.emacs.d/mininit.el" -l "tests/my-ert.el" -f ert-run-tests-batch-and-exit
