name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 28.2 # bookworm
          - 30.1 # bookworm-backports / trixie
          - snapshot
    steps:
      - name: Install Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          emacs --debug-init --batch -u $USER
          ./tests/check_daemon_starts.sh
          emacs -q --batch -l "tests/my-ert.el" -f ert-run-tests-batch-and-exit
          emacs -q --batch -l "~/.emacs.d/mininit.el" -l "tests/my-ert.el" -f ert-run-tests-batch-and-exit
